api/api/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static 
from django.conf import settings

from personal.views import (
	home_screen_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls', 'blog')),
    
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),


    #Rest_framework_Api's:-
    path('api/blog/', include('blog.api.urls', 'blog_api')),
    path('api-auth/', include('rest_framework.urls')),
    

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/blog/urls.py
  
from django.urls import path
from blog.views import(

	create_blog_view,
	detail_blog_view,
	edit_blog_view,

)

app_name = 'blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
]

api/personal/models.py
from django.db import models

 #Two tuple structure
 #The first element in each tuple is the value that will be stored in the database. The second element is displayed by the field’s form widget.
 #Tuple
PRIORITY = [
 	('L', 'Low'), #Tuple1
 	('M', 'Medium'), #Tuple2
 	('H', 'High'), #Tuple3
 ]

class Question(models.Model):
 	title		 			= models.CharField(max_length=60)
 	question 				= models.TextField(max_length=400)
 	priority 				= models.CharField(max_length=1, choices=PRIORITY)

 	def __str__(self):
 		return self.title


 	class Meta:
 		verbose_name = 'The Question'
 		verbose_name_plural = 'Questions from People'

api/personal/views.py
from django.shortcuts import render
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from blog.views import get_blog_queryset
from blog.models import BlogPost

BLOG_POSTS_PER_PAGE = 10

def home_screen_view(request):
	
	context = {}

	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)
	


	# Pagination
	page = request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)

	try:
		blog_posts = blog_posts_paginator.page(page)
	except PageNotAnInteger:
		blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
	except EmptyPage:
		blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts'] = blog_posts

	return render(request, "personal/home.html", context)

api/personal/templates/personal/base.html
<!DOCTYPE html>
<html lang=en>

<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>

<body>

{% include 'snippets/base_css.html' %}
{% include 'snippets/header.html' %} 

<!-- Body -->
<style type="text/css">
	.main{
		min-height: 100vh;
		height: 100%;
	}
</style>
<div class="main">
	{% block content %}

	{% endblock content %}
</div>
<!-- End Body -->

{% include 'snippets/footer.html' %}

</body>


</html>

api/personal/templates/personal/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<style type="text/css">
	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}
	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}
	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}
	.left-column{
		padding:0px;
	}
	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'codingwithmitch_logo.png' %}" width="72" height="72">
					<p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
	  					framework and you'll see why in this course.</p>
						{% comment %} <p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>  {% endcomment %}
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->
			
			<!-- Pagination -->
			{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}

		</div>
		<!-- end blog feed -->



		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'codingwithmitch_logo.png' %}" width="72" height="72">
				<p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
  					framework and you'll see why in this course.</p>
				{% comment %} <p class="m-auto"><a class="btn btn-primary" href="{% url 'create' %}">Create post</a></p> {% endcomment %}
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->

	</div>
</div>

{% endblock content %}